-- 우유와 요거트가 담긴 장바구니
/*
SELECT T1.CART_ID
FROM CART_PRODUCTS AS T1
INNER JOIN CART_PRODUCTS AS T2 ON T1.CART_ID = T2.CART_ID
WHERE T1.NAME = 'Milk' AND T2.NAME = 'Yogurt'
ORDER BY T1.CART_ID
*/
SELECT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID
                 FROM CART_PRODUCTS
                 WHERE NAME = 'Milk')
AND NAME = 'Yogurt'
ORDER BY CART_ID